### ISSUE TITLE
Memory leak in Multiplayer after 5 aug update

### ISSUE THREAD

**Issue by timofeevAS** [JavidPack/RecipeBrowser#109]
Hello, dear friend! We're playing with my friends with ur useful addon, and after update by 5 aug, my RAM trashing with .NET)))

Terraria server create trash RAM (~~7 MB by 1 second)

I'm really dont know. Pls fix it bro..

**Comment by JavidPack** [comment]
The auguest 5th update just updated localization, are you sure the memory leak isn't coming from some other mod? I know calamity currently has a memory leak, for example. 

In any case, test with just Recipe Browser enabled to confirm, then let me know.

**Comment by timofeevAS** [comment]
ASAP i will post there info for you.

Thanks!

**Comment by timofeevAS** [comment]
Hello. Test it with friends in Multiplayer. And 5mb per second memory leak, dont know why :(

UPD: MY friend with FAV recipes left from game and leave me 1GB RAM)))


UPD: We cant remove FAV recipes, how to do this, Explain pls))) we remove mod in file system and intall again, and fav recipes depends on hero?
