### ISSUE TITLE
Pinned UI flashing in Multiplayer

### ISSUE THREAD

**Issue by scha384** [JavidPack/RecipeBrowser#111]
When using pinned recipes in 1.4 tModLoader, the pinned recipes UI has flashing item tooltips on hover. On the left side of the close button, a flashing icon of the other player also appears. Dragging the window from there causes it to stay fixed to the mouse cursor until the game is restarted. This seems to have started to happen recently, as I've never seen it before.
**EDIT**: I also tried changing frame skip settings, but that didn't help either.

**Comment by scha384** [comment]
Seems to be fixed in 0.10.2

**Comment by JavidPack** [comment]
Interesting, I guess the network syncing bug was causing it to refresh constantly, thanks for noticing and closing the issue.
