### ISSUE TITLE
Stuck on "Recipe Browser: Rebuilding Loot Cache"

### ISSUE THREAD

**Issue by pavlukivan** [JavidPack/RecipeBrowser#14]
My mod list:
- Alchemist NPC
- Boss Checklist
- Calamity Mod
- Dual Wielding
- Fargowiltas
- Yet Another Boss Health Bar
- Luiafk
- Terraria Overhaul
- Thorium Mod
- Tremor Mod Remastered
- Which Mod Is This From

**Comment by JavidPack** [comment]
The solution is to disable Overhaul, reload (so the loot cache can be built), then enable overhaul again.

**Comment by pavlukivan** [comment]
Ok thanks! In case you don't plan to fix it, can you maybe include this in mod description?

**Comment by JavidPack** [comment]
No, it's Overhauls fault, the overhaul modder is fixing it in a future update.

**Comment by pavlukivan** [comment]
Ok, im closing this then, thanks for the help

**Comment by milkev** [comment]
is it possible to get a config to just... not generate the loot cache? im having this issue with almost every content mod i have installed and id rather not have to deal with it every time i launch the game. not to mention if i forget, clicking cancel doesnt even work. it just hangs the game on 'loading canceled'. also shift is supposed to skip building loot cache? i just held shift down for like 5 min and it didnt do anything...

**Comment by JavidPack** [comment]
The main culprits of this have long been fixed, are you sure you are on the latest recipe browser?

**Comment by milkev** [comment]
the mod browser says i am, v0.8.9? that seems to be the latest version. the mods that are causing issues are calamity and apachis classes mod. should i be taking that up with those devs?
(id still like a config if possible, though)

**Comment by JavidPack** [comment]
Those mods load find on my end. Usually its a recipe browser problem, but I don't know what it could be. You can post a client.log if you want, but he best option to solve this is to come to the discord and chat there, https://discord.gg/w8Hcwby . A config option could be good, but so much of the mod depends on this feature that it would be difficult to maintain and implemtent.
