### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by GentleMaggot** [JavidPack/RecipeBrowser#2]
the my game seems to crash a lot when i have the mod enabled and pick up items or when i'm near chests, last time i used this mod was one of its first iterations with didn't have finding things in chests nearby so there might be some issues in that function. i haven't seen anyone else complaining about crashes in the forum so maybe have a config option to disable chest search?
 i've been using the recipe browser from cheat sheet since it is still like the old version and havent had a crash since (played for a couple of hour to make sure)

**Comment by JavidPack** [comment]
If there is anything relevant in client-crashlog.txt or the My Games\Terraria\ModLoader\Logs folder that would help. If you could delete all those, then play until it crashes, and post the relevant logs, that would help.

**Comment by GentleMaggot** [comment]
there is no client-crashlog.txt, game probably crashed before tmod could register it, only crash log i can get is from windows

**Comment by JavidPack** [comment]
Well, whatever you can tell me. Your modlist (enabled.json) might also help spot problems.

**Comment by GentleMaggot** [comment]
at some point i disabled some mods leaving only some core ones that i really wanted to see if they caused conflict, i think i was left with BossChecklist, CalamityMod, Fargowiltas, MagicStorage, MoreAccessories, ShorterRespawn, ThoriumMod, WingSlot, RecipeBrowser. they are pretty standard mods to have, seen some people use them without any problem.

**Comment by GentleMaggot** [comment]
here is the windows crash report but i dont see anything out of the ordinary. i erased some personal information but the file is mostly intact

[Report.txt](https://github.com/JavidPack/RecipeBrowser/files/1350341/Report.txt)

**Comment by GentleMaggot** [comment]
well, had more time to do some testing and found out it was calamity all along... i feel like an ass for troubling you, your mod does seem to make the crash happen alot quicker somehow and that made me jump to conclusions.

so sorry for the trouble

**Comment by JavidPack** [comment]
No problem. If the crash is because of the interaction between 2 mods I can look into it, but if the crash happens when only calamity is enabled then that's their problem.

Reopen this issue if you find out that the problem is only possible when both mods are enabled and just calamity.
