### ISSUE TITLE
Index was outside the bounds of the array in RecipeBrowser.LootCacheManager.Setup

### ISSUE THREAD

**Issue by hiddenwolfe** [JavidPack/RecipeBrowser#29]
Keeps giving me this error
Index was outside the bounds of the array.
   at RecipeBrowser.LootCacheManager.Setup(Mod recipeBrowserMod) in D:\Documents\My Games\Terraria/ModLoader\Mod Sources\RecipeBrowser\LootCache.cs:line 372
   at RecipeBrowser.RecipeBrowser.PostAddRecipes() in D:\Documents\My Games\Terraria/ModLoader\Mod Sources\RecipeBrowser\RecipeBrowser.cs:line 169
   at Terraria.ModLoader.RecipeHooks.PostAddRecipes()
seems to be due to "D:\Documents\My Games\Terraria/ModLoader\Mod Sources\RecipeBrowser\LootCache.cs:line 372" not being a proper place to go to becuase of terraria\
Also had issues with 0.7 and thorium but if I disable with 0.8 thorium it still crashed.

**Comment by hiddenwolfe** [comment]
I tried putting the the folder there that you was in the .zip and it still gives the same error.

**Comment by JavidPack** [comment]
To add to this issue, someone else with this problem reported the following:

1: 1
2: 1200
3: 1
4: 1200

while a normal Terraria should report

1: 8401
2: 2401
3: 8401
4: 2401

Something is messing up the values for maxTilesX and Y for that user, cause is still unknown

**Comment by hiddenwolfe** [comment]
Thanks for the response, I'm going to check to see if it works now.

**Comment by hiddenwolfe** [comment]
OK it's still crashing. Here is the log.

Initialized translations with 287 lines.
Initialized translations with 287 lines.
1: 1
2: 1200
3: 1
4: 1200

**Comment by JavidPack** [comment]
I just replicated the problem by installing Terraria Overhaul and then disabling the mod. I guess just wait for a fix to Overhaul to remove this code:

```cs
Main.maxTilesX = 1;
Main.maxTilesY = 1200;
```
In the meantime, anyone using that mod please refrain from reloading mods after leaving a world. If you need to change mods and Overhaul is enabled, enable or disable mods and then restart tmodloader.
