### ISSUE TITLE
Keyboard unresponsive when closing from Beastiary

### ISSUE THREAD

**Issue by CoveredInChocolate** [JavidPack/RecipeBrowser#31]
This has happened to me twice.

I look up an item and double click RMB to see which mobs drop the item. When I close the window, the keyboard is unresponsive. You can't even click ESC to go to the menu which means you need to terminate the Terraria process from Windows. (Mouse still works, so the first time I could talk to a nearby shop keeper and go to the settings menu from there).

I am using two other mods: Anti-Social and luiafk, but I don't think they are to blame.

Other than that, it worked beautifully. :)

**Comment by JavidPack** [comment]
This happens when you have the text input box selected and then double right click. I'm looking into it, just try to unfocus the text box before double right clicking.
