### ISSUE TITLE
RecipeBrowser Allows Items to Be Imported to Server, Bypassing SSC

### ISSUE THREAD

**Issue by Yuogusy** [JavidPack/RecipeBrowser#37]
I apologize for posting what is essentially almost the exact same issue to two of your mods with a similar description, but a very similar big is present in both mods. I posted a similar issue that is affecting HEROsMod to its Issues section as well.

My server uses the SSC (Server Side Characters) mod to ensure players can't bring in items from single player games. RecipeBrowser allows them to bypass this. I found a player with a chest full of platinum coins, and was able to figure out two possibilities of how this was done, one being with this mod, the other being with HEROsMod. For this one,  first, I log out of my server character. Then using that same character, I create a single player world. Next, I take whatever item or stack of items I want and place it in the "Place Item Here" box as if I was looking up it's recipe. Then, leaving that window open, I exit the single player game. When I log  back into the multiplayer server using that character, the RecipeBrowser is open and the item is in there. Now I can just place it into my inventory on the multiplayer server.

Just like HEROsMod, this mod it is extremely helpful for servers, so any method you could give me to squash this bug would be greatly appreciated. At this point I am going to have to shut down my server until I can figure out how to prevent this on both mods. Thanks so much for the amazing mods!

**Comment by JavidPack** [comment]
K, I'll look into these.
