### ISSUE TITLE
Correct Latest version

### ISSUE THREAD

**Issue by jjspace** [JavidPack/RecipeBrowser#42]
Can you update and make any new changes to the latest version, version 8.x of the mod? I really like the multistep crafting but because your "latest" published versions are 7.x.x Mod Browser keeps thinking that version 7 is the one it should be downloading when version 8 has the really awesome multistep crafting.
Thanks for the wonderfully handy mod regardless.

**Comment by JavidPack** [comment]
The v8 bugs are a bit too much for me to spend the time figuring out at the current time. They'll eventually happen.
