### ISSUE TITLE
talon (from thorium mod) drop not shown

### ISSUE THREAD

**Issue by muniategui** [JavidPack/RecipeBrowser#7]
This item is implemented in thorium 1.4.1 and is not shown by which monster is dropped (should be Vultures). 
Also it could be that i'm handless with mods since i've started using them today and however others drops are found properly (i don't know if  more drops are missing)

**Comment by JavidPack** [comment]
Thanks, I know why, just not sure what impact a fix will have on the loot cache generation so I'll have to test it out.
