### ISSUE TITLE
[1.4.4] Recipe Browser cannot load, was built for 2022.xx.xx 

### ISSUE THREAD

**Issue by Setnour6** [JavidPack/RecipeBrowser#91]
Just to say it straightforward, there was a JIT problem something. I can't attach the client log because I ran it again and previous data got overridden, sorry.

To reproduce the issue, go to tModLoader 1.4.4 (through betas), enable the workshop uploaded version of Recipe Browser 1.4.4.x and reload the mods. A loading error of you are using "this version", however this mod is built for "that version" appears.

If you do not run into loading issues or any other issues after loading with your local version of recipe browser, can you please upload the new version of recipe browser to tModLoader? Thank you!

**Edit:** I decided to make a fork of this repository and port the mod to 1.4.4. Link: https://github.com/Setnour6/RecipeBrowser/tree/1.4.4

**Comment by JavidPack** [comment]
v0.10 has been published for 1.4.4
